# Generated by Django 4.0.6 on 2022-07-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0002_rename_familiares_familia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familia',
            new_name='Familiares',
        ),
    ]
